-- =============================================
-- TBL_PHONE 초기 데이터
-- =============================================
-- SORT_ORDER 기준
--   1 ~ 10 : 한국발 항공노선 주요 국가 (상단 고정)
--   99     : 일반 국가 (가나다/ABC 순)
-- COUNTRY_CD : ISO 3166-1 alpha-2
-- PHONE_CD   : ITU-T E.164, '+' 제외 숫자만
-- +1 공유 국가(미국·캐나다)는 별도 행으로 분리
-- =============================================

-- -----------------------------------------------
-- SORT_ORDER 1~10 : 주요 노선 상단 고정
-- -----------------------------------------------

-- 1. 대한민국
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('KR', '82', 'Y', 1, 'SYSTEM', 'SYSTEM');

-- 2. 일본
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('JP', '81', 'Y', 2, 'SYSTEM', 'SYSTEM');

-- 3. 중국
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('CN', '86', 'Y', 3, 'SYSTEM', 'SYSTEM');

-- 4. 미국
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('US', '1', 'Y', 4, 'SYSTEM', 'SYSTEM');

-- 5. 캐나다 (+1 공유, 별도 행)
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('CA', '1', 'Y', 5, 'SYSTEM', 'SYSTEM');

-- 6. 홍콩
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('HK', '852', 'Y', 6, 'SYSTEM', 'SYSTEM');

-- 7. 태국
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('TH', '66', 'Y', 7, 'SYSTEM', 'SYSTEM');

-- 8. 베트남
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('VN', '84', 'Y', 8, 'SYSTEM', 'SYSTEM');

-- 9. 싱가포르
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('SG', '65', 'Y', 9, 'SYSTEM', 'SYSTEM');

-- 10. 대만
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('TW', '886', 'Y', 10, 'SYSTEM', 'SYSTEM');

-- -----------------------------------------------
-- SORT_ORDER 99 : 일반 국가 (가나다순)
-- -----------------------------------------------

-- 그리스
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('GR', '30', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 네덜란드
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('NL', '31', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 노르웨이
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('NO', '47', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 뉴질랜드
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('NZ', '64', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 덴마크
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('DK', '45', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 독일
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('DE', '49', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 러시아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('RU', '7', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 말레이시아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('MY', '60', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 멕시코
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('MX', '52', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 모로코
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('MA', '212', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 몽골
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('MN', '976', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 미얀마
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('MM', '95', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 바레인
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('BH', '973', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 방글라데시
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('BD', '880', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 벨기에
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('BE', '32', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 브라질
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('BR', '55', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 사우디아라비아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('SA', '966', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 스웨덴
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('SE', '46', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 스위스
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('CH', '41', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 스페인
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('ES', '34', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 아랍에미리트
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('AE', '971', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 아르헨티나
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('AR', '54', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 아이슬란드
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('IS', '354', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 아일랜드
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('IE', '353', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 오만
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('OM', '968', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 오스트리아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('AT', '43', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 우즈베키스탄
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('UZ', '998', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 이스라엘
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('IL', '972', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 이집트
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('EG', '20', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 이탈리아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('IT', '39', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 인도
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('IN', '91', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 인도네시아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('ID', '62', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 영국
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('GB', '44', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 요르단
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('JO', '962', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 카자흐스탄
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('KZ', '7', 'Y', 99, 'SYSTEM', 'SYSTEM');
-- 주의: +7은 러시아(RU)와 공유. 러시아 행과 PHONE_CD 동일, COUNTRY_CD로 구분.

-- 카타르
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('QA', '974', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 캄보디아
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('KH', '855', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 쿠웨이트
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('KW', '965', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 튀르키예
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('TR', '90', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 파키스탄
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('PK', '92', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 파리/프랑스
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('FR', '33', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 필리핀
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('PH', '63', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 핀란드
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('FI', '358', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 호주
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('AU', '61', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 포르투갈
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('PT', '351', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 폴란드
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('PL', '48', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 체코
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('CZ', '420', 'Y', 99, 'SYSTEM', 'SYSTEM');

-- 헝가리
INSERT INTO TBL_PHONE (COUNTRY_CD, PHONE_CD, USE_YN, SORT_ORDER, RGTR_ID, MDFR_ID)
VALUES ('HU', '36', 'Y', 99, 'SYSTEM', 'SYSTEM');