-- 한국
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('ICN', 'RKSI', '인천국제공항', 'Incheon International Airport', '인천국제공항', 'KR', 'ICN', 37.469075, 126.450517, 'Asia/Seoul', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('GMP', 'RKSS', '김포국제공항', 'Gimpo International Airport', '김포국제공항', 'KR', 'SEL', 37.558069, 126.791014, 'Asia/Seoul', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('PUS', 'RKPK', '김해국제공항', 'Gimhae International Airport', '김해국제공항', 'KR', 'PUS', 35.179508, 128.938228, 'Asia/Seoul', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CJU', 'RKPC', '제주국제공항', 'Jeju International Airport', '제주국제공항', 'KR', 'CJU', 33.511267, 126.492967, 'Asia/Seoul', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('TAE', 'RKTN', '대구국제공항', 'Daegu International Airport', '대구국제공항', 'KR', 'TAE', 35.894061, 128.658764, 'Asia/Seoul', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CJJ', 'RKTU', '청주국제공항', 'Cheongju International Airport', '청주국제공항', 'KR', 'CJJ', 36.716558, 127.498869, 'Asia/Seoul', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 일본
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('NRT', 'RJAA', '나리타국제공항', 'Narita International Airport', '成田国際空港', 'JP', 'TYO', 35.764722, 140.386389, 'Asia/Tokyo', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('HND', 'RJTT', '하네다국제공항', 'Haneda Airport', '東京国際空港', 'JP', 'TYO', 35.552258, 139.779694, 'Asia/Tokyo', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('KIX', 'RJBB', '간사이국제공항', 'Kansai International Airport', '関西国際空港', 'JP', 'OSA', 34.427019, 135.244144, 'Asia/Tokyo', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CTS', 'RJCC', '신치토세공항', 'New Chitose Airport', '新千歳空港', 'JP', 'SPK', 42.775167, 141.692250, 'Asia/Tokyo', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('FUK', 'RJFF', '후쿠오카공항', 'Fukuoka Airport', '福岡空港', 'JP', 'FUK', 33.585942, 130.450794, 'Asia/Tokyo', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('OKA', 'ROAH', '나하공항', 'Naha Airport', '那覇空港', 'JP', 'OKA', 26.195819, 127.646294, 'Asia/Tokyo', 'B', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 중국
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('PEK', 'ZBAA', '베이징 수도 국제공항', 'Beijing Capital International Airport', '北京首都国际机场', 'CN', 'BJS', 40.080111, 116.584556, 'Asia/Shanghai', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('PVG', 'ZSPD', '상하이 푸둥 국제공항', 'Shanghai Pudong International Airport', '上海浦东国际机场', 'CN', 'SHA', 31.143378, 121.805214, 'Asia/Shanghai', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CAN', 'ZGGG', '광저우 바이윈 국제공항', 'Guangzhou Baiyun International Airport', '广州白云国际机场', 'CN', 'CAN', 23.392436, 113.299186, 'Asia/Shanghai', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 홍콩
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('HKG', 'VHHH', '홍콩 국제공항', 'Hong Kong International Airport', '香港國際機場', 'HK', 'HKG', 22.308919, 113.914603, 'Asia/Hong_Kong', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 대만
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('TPE', 'RCTP', '타이완 타오위안 국제공항', 'Taiwan Taoyuan International Airport', '臺灣桃園國際機場', 'TW', 'TPE', 25.077731, 121.232822, 'Asia/Taipei', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 싱가포르
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('SIN', 'WSSS', '싱가포르 창이 국제공항', 'Singapore Changi Airport', 'Singapore Changi Airport', 'SG', 'SIN', 1.359167, 103.989441, 'Asia/Singapore', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 태국
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('BKK', 'VTBS', '방콕 수완나품 국제공항', 'Suvarnabhumi Airport', 'ท่าอากาศยานสุวรรณภูมิ', 'TH', 'BKK', 13.681108, 100.747283, 'Asia/Bangkok', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('HKT', 'VTSP', '푸켓 국제공항', 'Phuket International Airport', 'ท่าอากาศยานภูเก็ต', 'TH', 'HKT', 8.113222, 98.316922, 'Asia/Bangkok', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 베트남
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('SGN', 'VVTS', '호치민 떤선녓 국제공항', 'Tan Son Nhat International Airport', 'Sân bay quốc tế Tân Sơn Nhất', 'VN', 'SGN', 10.818797, 106.651922, 'Asia/Ho_Chi_Minh', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('HAN', 'VVNB', '하노이 노이바이 국제공항', 'Noi Bai International Airport', 'Sân bay quốc tế Nội Bài', 'VN', 'HAN', 21.221186, 105.807178, 'Asia/Ho_Chi_Minh', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('DAD', 'VVDN', '다낭 국제공항', 'Da Nang International Airport', 'Sân bay quốc tế Đà Nẵng', 'VN', 'DAD', 16.043917, 108.199181, 'Asia/Ho_Chi_Minh', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 필리핀
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('MNL', 'RPLL', '마닐라 니노이 아키노 국제공항', 'Ninoy Aquino International Airport', 'Paliparan Internasyonal ng Ninoy Aquino', 'PH', 'MNL', 14.508472, 121.019722, 'Asia/Manila', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CEB', 'RPVM', '막탄-세부 국제공항', 'Mactan-Cebu International Airport', 'Mactan-Cebu International Airport', 'PH', 'CEB', 10.307542, 123.978856, 'Asia/Manila', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 말레이시아
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('KUL', 'WMKK', '쿠알라룸푸르 국제공항', 'Kuala Lumpur International Airport', 'Lapangan Terbang Antarabangsa Kuala Lumpur', 'MY', 'KUL', 2.745578, 101.709917, 'Asia/Kuala_Lumpur', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 인도네시아
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CGK', 'WIII', '자카르타 수카르노-하타 국제공항', 'Soekarno-Hatta International Airport', 'Bandara Internasional Soekarno-Hatta', 'ID', 'JKT', -6.125567, 106.655897, 'Asia/Jakarta', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('DPS', 'WADD', '발리 응우라라이 국제공항', 'Ngurah Rai International Airport', 'Bandara Internasional I Gusti Ngurah Rai', 'ID', 'DPS', -8.748169, 115.167214, 'Asia/Makassar', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 인도
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('DEL', 'VIDP', '뉴델리 인디라 간디 국제공항', 'Indira Gandhi International Airport', 'इंदिरा गांधी अंतर्राष्ट्रीय हवाई अड्डा', 'IN', 'DEL', 28.556600, 77.100797, 'Asia/Kolkata', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('BOM', 'VABB', '뭄바이 차트라파티 시바지 마하라지 국제공항', 'Chhatrapati Shivaji Maharaj International Airport', 'छत्रपती शिवाजी महाराज आंतरराष्ट्रीय विमानतळ', 'IN', 'BOM', 19.088686, 72.867919, 'Asia/Kolkata', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- UAE
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('DXB', 'OMDB', '두바이 국제공항', 'Dubai International Airport', 'مطار دبي الدولي', 'AE', 'DXB', 25.252778, 55.364444, 'Asia/Dubai', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('AUH', 'OMAA', '아부다비 국제공항', 'Abu Dhabi International Airport', 'مطار أبوظبي الدولي', 'AE', 'AUH', 24.432972, 54.651138, 'Asia/Dubai', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 미국
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('JFK', 'KJFK', '뉴욕 존 F. 케네디 국제공항', 'John F. Kennedy International Airport', 'John F. Kennedy International Airport', 'US', 'NYC', 40.639722, -73.778889, 'America/New_York', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('LAX', 'KLAX', '로스앤젤레스 국제공항', 'Los Angeles International Airport', 'Los Angeles International Airport', 'US', 'LAX', 33.942536, -118.408075, 'America/Los_Angeles', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('ORD', 'KORD', '시카고 오헤어 국제공항', "Chicago O'Hare International Airport", "Chicago O'Hare International Airport", 'US', 'CHI', 41.978603, -87.904842, 'America/Chicago', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('SFO', 'KSFO', '샌프란시스코 국제공항', 'San Francisco International Airport', 'San Francisco International Airport', 'US', 'SFO', 37.618972, -122.374889, 'America/Los_Angeles', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 호주
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('SYD', 'YSSY', '시드니 킹스포드스미스 국제공항', 'Sydney Airport', 'Sydney Airport', 'AU', 'SYD', -33.946110, 151.177222, 'Australia/Sydney', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('MEL', 'YMML', '멜버른 국제공항', 'Melbourne Airport', 'Melbourne Airport', 'AU', 'MEL', -37.673333, 144.843333, 'Australia/Melbourne', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 괌 (미국 자치령, COUNTRY_CD = US)
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('GUM', 'PGUM', '괌 안토니오 B. 원 팻 국제공항', 'Antonio B. Won Pat International Airport', 'Antonio B. Won Pat International Airport', 'US', 'GUM', 13.483417, 144.796061, 'Pacific/Guam', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 사이판 (미국 자치령, COUNTRY_CD = US)
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('SPN', 'PGSN', '사이판 국제공항', 'Saipan International Airport', 'Saipan International Airport', 'US', 'SPN', 15.119000, 145.729000, 'Pacific/Saipan', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 캐나다
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('YVR', 'CYVR', '밴쿠버 국제공항', 'Vancouver International Airport', 'Vancouver International Airport', 'CA', 'YVR', 49.193889, -123.184444, 'America/Vancouver', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 이집트
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CAI', 'HECA', '카이로 국제공항', 'Cairo International Airport', 'مطار القاهرة الدولي', 'EG', 'CAI', 30.121944, 31.405556, 'Africa/Cairo', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 튀르키예
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('IST', 'LTFM', '이스탄불 공항', 'Istanbul Airport', 'İstanbul Havalimanı', 'TR', 'IST', 41.275278, 28.751944, 'Europe/Istanbul', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 영국
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('LHR', 'EGLL', '런던 히드로 국제공항', 'London Heathrow Airport', 'London Heathrow Airport', 'GB', 'LON', 51.477500, -0.461389, 'Europe/London', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('LGW', 'EGKK', '런던 개트윅 공항', 'London Gatwick Airport', 'London Gatwick Airport', 'GB', 'LON', 51.148056, -0.190278, 'Europe/London', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('MAN', 'EGCC', '맨체스터 공항', 'Manchester Airport', 'Manchester Airport', 'GB', 'MAN', 53.353750, -2.274950, 'Europe/London', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 프랑스
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CDG', 'LFPG', '파리 샤를 드 골 국제공항', 'Charles de Gaulle Airport', 'Aéroport Paris-Charles-de-Gaulle', 'FR', 'PAR', 49.009691, 2.547925, 'Europe/Paris', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('ORY', 'LFPO', '파리 오를리 공항', 'Paris Orly Airport', 'Aéroport de Paris-Orly', 'FR', 'PAR', 48.723333, 2.379444, 'Europe/Paris', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 독일
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('FRA', 'EDDF', '프랑크푸르트 국제공항', 'Frankfurt Airport', 'Flughafen Frankfurt Main', 'DE', 'FRA', 50.033333, 8.570556, 'Europe/Berlin', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('MUC', 'EDDM', '뮌헨 국제공항', 'Munich Airport', 'Flughafen München', 'DE', 'MUC', 48.353783, 11.786086, 'Europe/Berlin', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 네덜란드
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('AMS', 'EHAM', '암스테르담 스키폴 국제공항', 'Amsterdam Airport Schiphol', 'Amsterdam Airport Schiphol', 'NL', 'AMS', 52.308600, 4.763889, 'Europe/Amsterdam', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 벨기에
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('BRU', 'EBBR', '브뤼셀 국제공항', 'Brussels Airport', 'Luchthaven Brussel', 'BE', 'BRU', 50.901389, 4.484444, 'Europe/Brussels', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 스위스
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('ZRH', 'LSZH', '취리히 국제공항', 'Zurich Airport', 'Flughafen Zürich', 'CH', 'ZRH', 47.464722, 8.549167, 'Europe/Zurich', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('GVA', 'LSGG', '제네바 국제공항', 'Geneva Airport', 'Aéroport international de Genève', 'CH', 'GVA', 46.237222, 6.108889, 'Europe/Zurich', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 오스트리아
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('VIE', 'LOWW', '빈 국제공항', 'Vienna International Airport', 'Flughafen Wien-Schwechat', 'AT', 'VIE', 48.110833, 16.570833, 'Europe/Vienna', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 이탈리아
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('FCO', 'LIRF', '로마 피우미치노 국제공항', 'Leonardo da Vinci International Airport', 'Aeroporto di Roma-Fiumicino', 'IT', 'ROM', 41.804475, 12.250797, 'Europe/Rome', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('MXP', 'LIMC', '밀라노 말펜사 국제공항', 'Milan Malpensa Airport', 'Aeroporto di Milano-Malpensa', 'IT', 'MIL', 45.630606, 8.723078, 'Europe/Rome', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 스페인
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('MAD', 'LEMD', '마드리드 아돌포 수아레스 국제공항', 'Adolfo Suárez Madrid-Barajas Airport', 'Aeropuerto Adolfo Suárez Madrid-Barajas', 'ES', 'MAD', 40.471926, -3.560833, 'Europe/Madrid', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('BCN', 'LEBL', '바르셀로나 엘프라트 국제공항', 'Barcelona-El Prat Airport', 'Aeroport de Barcelona-El Prat', 'ES', 'BCN', 41.297078, 2.078464, 'Europe/Madrid', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('PMI', 'LEPA', '팔마 데 마요르카 공항', 'Palma de Mallorca Airport', 'Aeroport de Palma', 'ES', 'PMI', 39.551667, 2.738819, 'Europe/Madrid', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 포르투갈
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('LIS', 'LPPT', '리스본 움베르토 델가도 국제공항', 'Humberto Delgado Airport', 'Aeroporto Humberto Delgado', 'PT', 'LIS', 38.774167, -9.134167, 'Europe/Lisbon', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 그리스
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('ATH', 'LGAV', '아테네 엘레프테리오스 베니젤로스 국제공항', 'Athens International Airport', 'Διεθνής Αερολιμένας Αθηνών', 'GR', 'ATH', 37.936358, 23.944467, 'Europe/Athens', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 폴란드
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('WAW', 'EPWA', '바르샤바 쇼팽 국제공항', 'Warsaw Chopin Airport', 'Lotnisko Chopina w Warszawie', 'PL', 'WAW', 52.165694, 20.967081, 'Europe/Warsaw', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 체코
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('PRG', 'LKPR', '프라하 바츨라프 하벨 국제공항', 'Václav Havel Airport Prague', 'Letiště Václava Havla Praha', 'CZ', 'PRG', 50.100833, 14.260000, 'Europe/Prague', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 헝가리
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('BUD', 'LHBP', '부다페스트 페렌츠 리스트 국제공항', 'Budapest Ferenc Liszt International Airport', 'Budapest Liszt Ferenc Nemzetközi Repülőtér', 'HU', 'BUD', 47.439167, 19.261111, 'Europe/Budapest', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 아일랜드
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('DUB', 'EIDW', '더블린 국제공항', 'Dublin Airport', 'Aerfort Bhaile Átha Cliath', 'IE', 'DUB', 53.421333, -6.270075, 'Europe/Dublin', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 노르웨이
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('OSL', 'ENGM', '오슬로 가르데르모엔 공항', 'Oslo Gardermoen Airport', 'Oslo lufthavn, Gardermoen', 'NO', 'OSL', 60.193917, 11.100361, 'Europe/Oslo', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 스웨덴
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('ARN', 'ESSA', '스톡홀름 알란다 국제공항', 'Stockholm Arlanda Airport', 'Stockholms flygplats Arlanda', 'SE', 'STO', 59.651944, 17.918611, 'Europe/Stockholm', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 덴마크
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('CPH', 'EKCH', '코펜하겐 카스트루프 국제공항', 'Copenhagen Airport', 'Københavns Lufthavn, Kastrup', 'DK', 'CPH', 55.617917, 12.655972, 'Europe/Copenhagen', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 핀란드
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('HEL', 'EFHK', '헬싱키 반타 국제공항', 'Helsinki-Vantaa Airport', 'Helsinki-Vantaan lentoasema', 'FI', 'HEL', 60.317222, 24.963333, 'Europe/Helsinki', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 아이슬란드
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('KEF', 'BIKF', '케플라비크 국제공항', 'Keflavík International Airport', 'Keflavíkurflugvöllur', 'IS', 'REK', 63.985000, -22.605556, 'Atlantic/Reykjavik', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

-- 러시아
INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('SVO', 'UUEE', '모스크바 셰레메티예보 국제공항', 'Sheremetyevo International Airport', 'Международный аэропорт Шереметьево', 'RU', 'MOW', 55.972642, 37.414589, 'Europe/Moscow', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_AIRPORT (IATA_CD, ICAO_CD, AIRPORT_KOR_NM, AIRPORT_ENG_NM, AIRPORT_NAT_NM, COUNTRY_CD, CITY_CD, LATITUDE, LONGITUDE, TIMEZONE, AIRPORT_TYPE_CD, AIRPORT_STAT_CD, USE_YN, RGTR_ID, MDFR_ID)
VALUES ('DME', 'UUDD', '모스크바 도모데도보 국제공항', 'Domodedovo International Airport', 'Международный аэропорт Домодедово', 'RU', 'MOW', 55.408611, 37.906111, 'Europe/Moscow', 'I', 'OP', 'Y', 'SYSTEM', 'SYSTEM');