-- 공항 유형 코드 그룹
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('ROOT', 'AIRPORT_TYPE', '공항유형', 'Airport Type', '공항 운영 유형 분류 코드', 0, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_TYPE', 'D', '국내선', 'Domestic', '국내선 전용 공항', 1, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_TYPE', 'I', '국제선', 'International', '국제선 전용 공항', 2, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_TYPE', 'B', '복합', 'Both', '국내선/국제선 복합 공항', 3, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 공항 상태 코드 그룹
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('ROOT', 'AIRPORT_STAT', '공항상태', 'Airport Status', '공항 운영 상태 코드', 0, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_STAT', 'OP', '운영중', 'Operational', '정상 운영 중인 공항', 1, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_STAT', 'CL', '영구폐쇄', 'Closed', '영구적으로 폐쇄된 공항', 2, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_STAT', 'TC', '임시폐쇄', 'Temporarily Closed', '일시적으로 운영 중단된 공항', 3, 'Y', 'N', 'SYSTEM', 'SYSTEM');

INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('AIRPORT_STAT', 'CN', '공사중', 'Under Construction', '신설 또는 확장 공사 중인 공항', 4, 'Y', 'N', 'SYSTEM', 'SYSTEM');


-- 유럽 - 독일
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'MUC', '뮌헨', 'Munich', 'MUC(뮌헨국제공항)', 631, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 영국
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'MAN', '맨체스터', 'Manchester', 'MAN(맨체스터공항)', 611, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 스위스
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'GVA', '제네바', 'Geneva', 'GVA(제네바국제공항)', 681, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 노르웨이
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'OSL', '오슬로', 'Oslo', 'OSL(오슬로 가르데르모엔공항)', 710, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 스웨덴
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'STO', '스톡홀름', 'Stockholm', 'ARN(알란다국제공항)', 720, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 덴마크
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'CPH', '코펜하겐', 'Copenhagen', 'CPH(코펜하겐 카스트루프공항)', 730, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 핀란드
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'HEL', '헬싱키', 'Helsinki', 'HEL(헬싱키 반타공항)', 740, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 포르투갈
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'LIS', '리스본', 'Lisbon', 'LIS(리스본 움베르토 델가도공항)', 750, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 그리스
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'ATH', '아테네', 'Athens', 'ATH(아테네 엘레프테리오스 베니젤로스공항)', 760, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 폴란드
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'WAW', '바르샤바', 'Warsaw', 'WAW(바르샤바 쇼팽공항)', 770, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 벨기에
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'BRU', '브뤼셀', 'Brussels', 'BRU(브뤼셀 국제공항)', 780, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 체코
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'PRG', '프라하', 'Prague', 'PRG(프라하 바츨라프 하벨공항)', 790, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 헝가리
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'BUD', '부다페스트', 'Budapest', 'BUD(부다페스트 페렌츠 리스트공항)', 800, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 아일랜드
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'DUB', '더블린', 'Dublin', 'DUB(더블린 국제공항)', 801, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 아이슬란드
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'REK', '레이캬비크', 'Reykjavik', 'KEF(케플라비크 국제공항)', 802, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 이탈리아
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'MIL', '밀라노', 'Milan', 'MXP(말펜사국제공항), LIN(리나테공항)', 651, 'Y', 'N', 'SYSTEM', 'SYSTEM');

-- 유럽 - 스페인
INSERT INTO TBL_COMMON_CODE (UP_CD, CD, CD_KOR_NM, CD_ENG_NM, DESCRIPTION, SORT_ORDER, USE_YN, DEL_YN, RGTR_ID, MDFR_ID)
VALUES ('CITY', 'PMI', '항 데 마요르카', 'Palma de Mallorca', 'PMI(팔마 데 마요르카공항)', 671, 'Y', 'N', 'SYSTEM', 'SYSTEM');